app:
  ports:
    - 8080:8080/tcp
    - 9090:9090/tcp
  log_driver: ''
  restart: always
  log_opt: {}
  links:
    - db
  image: srik/dev-image
  volumes:
    - ./grails-petclinic:/grails-petclinic
    - ./grails-petclinic/.grails:/root/.grails/
  environment:
    DB_HOST: db:3306
    DB_PASSWORD: pass1
db:
  environment:
    MYSQL_ROOT_PASSWORD: pass1
    MYSQL_DATABASE: default
    MYSQL_USER: admin
    MYSQL_PASSWORD: pass1
  restart: always
  ports:
    - 3306:3306/tcp
  tty: true
  image: mysql:5.7
  stdin_open: true